### ISSUE TITLE
initialize endpoint

### ISSUE THREAD

**Issue by bradcgarner** [brianjb-lfl/npmatch#10]
This is for the endpoint that initializes the app.  Causes & skills are fine.  For the 'userArr' variable (in the server), please populate it with:
typeOf === 'organization';
fields: id, organization, bio, logo, all location fields, links, causes

**Comment by brianjb-lfl** [comment]
I've updated the user fields and filter.  The nested arrays will take a little bit - working that on a branch.

**Comment by brianjb-lfl** [comment]
done.
