### ISSUE TITLE
create opportunity endpoint

### ISSUE THREAD

**Issue by bradcgarner** [brianjb-lfl/npmatch#11]
Brian: I added this fetch to the front-end.
POST to api/opportunities
Protected endpoint
Will send to the server an object matching the opportunity object in potential-states.js
Let's save validation of which keys are present for later; for now, please accept any combination of keys IN THE ROOT OBJECT.  I.e. any keys not commented as SQL Join in potential-states.
(Let's decide if keys commented as SQL join will be sent via separate endpoint (probably cleaner) or combined with this later.)

**Comment by brianjb-lfl** [comment]
I already had this in place with nominal field checks (title, narrative and user id).  Opportunity pretty empty without that info so I'm leaving them for now.  If they cause trouble I can comment out tomorrow.
