### ISSUE TITLE
1. Change timestamps to integers or get to work with server as timestamps

### ISSUE THREAD

**Issue by bradcgarner** [brianjb-lfl/npmatch#23]
Opportunities is only table affected. Timestamps are not working.

Current
  timestamp_start timestamp,
  timestamp_end timestamp,

Proposed
  date_start_year integer,
  date_start_month integer,
  date_start_day integer,
  date_end_year integer,
  date_end_month integer,
  date_end_day integer,

**Comment by brianjb-lfl** [comment]
I thought you meant a single integer (kind of like Excel's 1900 referenced dateserial).  I don't see the point of this.  If we're going to break this into its pieces why don't we just store it as a date - date_start = new Date(year, month, day)?  Let's go over this with Ben P.
