### ISSUE TITLE
initialize endpoint

### ISSUE THREAD

**Issue by bradcgarner** [brianjb-lfl/npmatch#7]
We need an endpoint to initialize the app when it first loads.  I suggest 'api/initialize' but it could be something else.  It should accept no arguments and be unprotected.  It should return an object:
{
causes: [array of strings of all causes],
skills: [array of strings of all skills],
usersList: [list of users, with opportunities... for now can be all, but we will narrow that down later]

**Comment by brianjb-lfl** [comment]
Added api/admin/initialize tests and endpoint.  Everything tested sat.  Per our discussion, the user list part is just returning users until we figure out how we want to incorporate opportunities.
